FROM ubuntu:latest
MAINTAINER André Stato <tstato@gmail.com>

ENV TZ=America/Sao_Paulo


RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" TZ="Amercia/Sao_Paulo" apt-get -y install tzdata
RUN apt-get install -y apache2 curl wget git


ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

EXPOSE 80

CMD /usr/sbin/apache2ctl -D FOREGROUND
